apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-103-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 103-log-output
  template:
    metadata:
      labels:
        app: 103-log-output
    spec:
      containers:
        - name: 103-log-output
          image: tuplawee7/101-log-output:latest
