apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-v04-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-v04
  template:
    metadata:
      labels:
        app: project-v04
    spec:
      containers:
        - name: project-v04
          image: tuplawee7/105-project-v03
