apiVersion: v1
kind: Service
metadata:
  name: project-v04-svc
spec:
  type: NodePort
  selector:
    app: project-v04
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 8080
